name: commit

on: push

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: 10.0.x
      - run: dotnet publish src/TeleDisk.csproj -c Release /t:PublishContainer -p:ContainerRegistry=ghcr.io -p:ContainerRepository=${{ github.repository_owner }}/teledisk -p:ContainerImageTag=latest "-p:ContainerRuntimeIdentifiers=linux-x64;linux-arm64"
        env:
          DOTNET_CONTAINER_REGISTRY_UNAME: ${{ github.actor }}
          DOTNET_CONTAINER_REGISTRY_PWORD: ${{ secrets.GITHUB_TOKEN }}
